#243: Add type field to LB data files
DARMA-tasking/LB-analysis-framework pull request #244
Opened 2022-05-06 15:00 UTC by marcinwrobel1986

### THIS PR:
- modified schemaValidator in order to support another schema
- added schema type and support checking
- modified synthetic lbaf data in order to be supported
- fixed all tests

Closes #243

2022-05-06 15:25 UTC, marcinwrobel1986 commented
Hello @nlslatt @lifflander @ppebay ,
please take a look at `src/lbaf/IO/schemaValidator.py` and check if there are some keys, that should be optional
Thanks!

2022-05-06 17:00 UTC, nlslatt reviewed
Do we still need tests of the stats schema? I marked some stuff that should be optional, but more discussion is needed to decide on whether other parts can be made optional.

@lifflander We talked early on about potentially allowing only a subset of statistical quantities to be output. Now that we're using json and are planning for a tool that extracts the desired quantities, do we still want to make any of them (e.g., kurtosis) optional in the schema? Do we want to make any of the statistics types (like comm or modeled vs. raw) optional?

2022-05-09 08:59 UTC, marcinwrobel1986 commented on src/lbaf/Utils/JSON_data_files_validator.py
> +            raise TypeError("JSON data is missing 'type' key")
That is a good question if we are planning to use `JSON_data_files_validator.py` for files other than VT. `LBStatsfile` schema was added to `SchemaValidator`, so at the moment `JSON_data_files_validator.py` checks if type of the data is "LBDatafile" or "LBStatsfile" and then proceed schema checking accordingly.

2022-05-18 17:43 UTC, nlslatt commented on src/lbaf/Utils/JSON_data_files_validator.py
> +            raise TypeError("JSON data is missing 'type' key")
Let's make it an automatic pass if it doesn't have one of the matching scheme types.

2022-05-23 11:01 UTC, marcinwrobel1986 commented on src/lbaf/Utils/JSON_data_files_validator.py
> +            raise TypeError("JSON data is missing 'type' key")
ok

2022-05-23 12:13 UTC, ppebay requested changes

2022-05-23 12:13 UTC, ppebay commented on src/lbaf/IO/schemaValidator.py
> +                            error=f"{self.get_error_message(allowed_types)} needs to be chosen"),
needs to ==> must be (everywhere not only here)

2022-05-23 12:13 UTC, ppebay commented on src/lbaf/IO/schemaValidator.py
> +        raise TypeError(f"Not supported schema type: {self.schema_type} were given")
Unsupported

2022-05-23 12:13 UTC, ppebay commented on src/lbaf/IO/schemaValidator.py
>          """ Returns True is schema_to_validate is valid with self.valid_schema else False. """
There is a problem in this sentence : I think the first `is` should be `if`

2022-05-23 12:13 UTC, ppebay commented on src/lbaf/Utils/JSON_data_files_validator.py
> -            print(f"=> Valid JSON schema in {file_path}")
No arrow

2022-05-23 20:39 UTC, ppebay approved these changes

2022-05-23 20:40 UTC, ppebay commented on src/lbaf/Utils/JSON_data_files_validator.py
> +            raise TypeError("JSON data is missing 'type' key")
Is this resolved?

2022-05-23 20:40 UTC, ppebay commented on src/lbaf/IO/schemaValidator.py
> +                        "post-LB": {
Resolved?

2022-05-23 20:42 UTC, marcinwrobel1986 commented on src/lbaf/Utils/JSON_data_files_validator.py
> +            raise TypeError("JSON data is missing 'type' key")
Yes, it's passing as Nicole requested.

2022-05-23 20:49 UTC, nlslatt commented
@marcinwrobel1986 Are there any tests of the `LBStatsfile` schema like there are of the `LBDatafile` one?

2022-05-23 20:51 UTC, nlslatt commented
@marcinwrobel1986 Please make meaningful commit messages for commit `1d5add0878ca2c93d6ce00a9ce511cbf973efd6c`. `merged develop` does not accurately describe the changes.

2022-05-23 20:58 UTC, marcinwrobel1986 commented
> @marcinwrobel1986 Please make meaningful commit messages for commit `1d5add0878ca2c93d6ce00a9ce511cbf973efd6c`. `merged develop` does not accurately describe the changes.

Hi @nlslatt sorry, but I missed that the previous message regarding develop merge was sent
![Zrzut ekranu z 2022-05-23 22-55-58](https://user-images.githubusercontent.com/47597569/169905010-32f7a675-e87f-4bf7-b92d-826d401ebccc.png)

2022-05-23 21:05 UTC, marcinwrobel1986 commented
> @marcinwrobel1986 Are there any tests of the `LBStatsfile` schema like there are of the `LBDatafile` one?

Tests for `JSON_data_files_validator.py` are on the branch `201-..` and will be probably merged tomorrow. I will write some regarding `LBStatsfile`, as well, because there are none at the moment.

2022-05-24 00:07 UTC, nlslatt approved these changes

2022-05-24 10:29 UTC, merged