#282: Modified VT data extractor to work without importing Brotli and concurrent
DARMA-tasking/LB-analysis-framework pull request #284
Opened 2022-09-01 16:21 UTC by marcinwrobel1986

### THIS PR:
- added multiprocessing to vt_data_extractor.py
- made brotli optional
- updated readme file

closes #282

2022-10-04 11:01 UTC, marcinwrobel1986 commented
@ppebay @lifflander Tests added coverage shows 57%, but in real it is more than 90%, becasue it is multiprocessing and I can not control the processes, just the output.

2022-10-07 19:36 UTC, ppebay commented
@marcinwrobel1986 is it alright for me to review it now?

2022-10-07 19:36 UTC, marcinwrobel1986 commented
@ppebay yes

2022-10-07 19:40 UTC, ppebay requested changes
Remove all exclamation marks in messages
Put all-caps words in lower case

Thanks

2022-10-07 19:40 UTC, ppebay commented on src/lbaf/Utils/vt_data_extractor.py
> +            raise SystemExit("Input data directory NOT FOUND!")
No exclamation marks 
No all-caps

2022-10-07 19:40 UTC, ppebay commented on src/lbaf/Utils/vt_data_extractor.py
> +                    raise SystemExit("Phase range wrongly declared!")
Same comment as above

2022-10-08 07:59 UTC, marcinwrobel1986 commented
@ppebay all done. All checks passed.

2022-10-08 11:37 UTC, ppebay approved these changes
Looking good

2022-10-08 11:38 UTC, merged