324 implement centralized memory constraint
DARMA-tasking/LB-analysis-framework pull request #325
Opened 2022-12-09 21:55 UTC by lifflander

Fixes #324 

Still very much a draft. Need to figure out better way for comparison operator.

2022-12-10 10:53 UTC, ppebay reviewed
First pass with suggestions as this PR is still `WIP`

2022-12-10 10:53 UTC, ppebay commented on src/lbaf/Execution/lbsCentralizedPrefixOptimizerAlgorithm.py
> +        self._logger.info("try bin: {}, size={}, id={}; assigned={}, rejected={}\n".format(tbin, size, sid, tally_assigned, tally_rejected))
In LBAF we try to use f-strings everywhere for code style consistency

2023-02-01 18:22 UTC, lifflander commented on src/lbaf/Applications/LBAF_app.py
> +        # # Instantiate phase to VT file writer if started from a log file
This needs to be fixed

2023-02-01 18:22 UTC, lifflander commented on src/lbaf/Utils/logger.py
> +    clr_fnc = yellow if config.get("terminal_background") == "light" else light_white
I need to fix this also

2023-02-26 08:34 UTC, ppebay commented on src/lbaf/Applications/LBAF_app.py
> +        # # Instantiate phase to VT file writer if started from a log file
Yes and done in PR #346

2023-02-26 08:57 UTC, ppebay approved these changes
PR approved but creating follow-on issue for documentation #348

2023-02-26 08:57 UTC, ppebay commented on src/lbaf/Utils/logger.py
> +    clr_fnc = yellow if config.get("terminal_background") == "light" else light_white
Agree, created #347 for that purpose

2023-02-26 08:58 UTC, ppebay commented
Reviewed/approved -- @lifflander please feel free to merge if you do not intend to make additional changes to this PR.

2023-06-15 08:30 UTC, ppebay requested changes
Thanks for the change; I made some other comments however

2023-06-15 08:30 UTC, ppebay commented on src/lbaf/Applications/LBAF_app.py
> +        if self.__parameters.algorithm["name"] != "CentralizedPrefixOptimizer":
I don't understand why logging `Starting centralized prefix optimizer` if the algorithm is **not** the `CentralizedPrefixOptimizer`

2023-06-15 08:30 UTC, ppebay commented on src/lbaf/Model/lbsRank.py
> +    def __lt__(self, other):
I am not sure that we want this to be always the comparison operator between ranks, as they can be sorted by other QoIs (like index, work, etc.)

2023-07-20 09:44 UTC, ppebay commented on src/lbaf/Execution/lbsCentralizedPrefixOptimizerAlgorithm.py
> +from ..Model.lbsPhase import Phase
Resolved

2023-07-20 09:46 UTC, ppebay commented on src/lbaf/Execution/lbsCentralizedPrefixOptimizerAlgorithm.py
> +        self._max_shared_ids = max_shared_ids + 1
Reorganized constructor to make this clearer

2023-07-20 09:49 UTC, ppebay commented on src/lbaf/Applications/LBAF_app.py
> +        if self.__parameters.algorithm["name"] != "CentralizedPrefixOptimizer":
Removed this logging line which in any event indicates the opposite of what it means

2023-07-20 09:50 UTC, ppebay commented on src/lbaf/Model/lbsRank.py
> +    def __lt__(self, other):
Leaving this as default comparison but creating follow-on issue for later discussion of how we want to handle this in general (and be consistent with vt in this regard)

2023-07-20 09:51 UTC, ppebay approved these changes
Made requested changes

2023-07-20 17:08 UTC, lifflander commented
Your changes look good to me. I can't approve it because it's my PR.

Were you going to to change the `<` operator to be more general than just compare load?

2023-07-20 17:11 UTC, ppebay commented
@lifflander #412

2023-07-20 17:12 UTC, merged