#351: Schema validator updates file with invalid output when behind VPN
DARMA-tasking/LB-analysis-framework pull request #357
Opened 2023-03-08 18:49 UTC by tlamonthezie

Fixes #351

2023-03-20 19:54 UTC, ppebay requested changes
* more comments needed to explain code
* f-strings should be used rather than `%s`
* style rule: use double-quotes for non-single-character strings

2023-03-20 19:54 UTC, ppebay commented on src/lbaf/Applications/LBAF_app.py
Bad option value `W0718` revealed by GitHub action; other Github actions findings (e.g. bad placement of `import` statement).

2023-03-20 19:54 UTC, ppebay commented on src/lbaf/Utils/logger.py
> +        level: Union[str, None] = 'info',
Please use double quotes for strings that are longer than a single character (this is one of the unwritten style rules of LBAF)

2023-03-20 19:54 UTC, ppebay commented on src/lbaf/Applications/LBAF_app.py
> +            default='conf.yaml'
use double quotes

2023-03-20 19:54 UTC, ppebay commented on src/lbaf/Applications/LBAF_app.py
> +        parser.add_argument("--config",
I suggest that we use a non-abbreviated option (`--configuration`) for the long form of the this flag, possibly with an added short form as well for convenience (`-c`).

2023-03-20 19:54 UTC, ppebay commented on src/lbaf/Applications/LBAF_app.py
> -            raise ConnectionError('Probably there is no internet connection') from err
' --> "

2023-03-20 19:54 UTC, ppebay commented on src/lbaf/Applications/LBAF_app.py
> +                            'Unexpected Content-Type (%s) for SchemaValidator file.'
Please use f-strings and double quotes

2023-04-25 16:50 UTC, tlamonthezie commented on src/lbaf/Applications/LBAF_app.py
> +                script_name = "JSON_data_files_validator.py"
Hello Philippe, I finally moved the schema validator download logic to a separated module I think it is more clear

2023-04-26 16:11 UTC, ppebay approved these changes
Second review approved

2023-04-26 16:11 UTC, merged