#441: Run new performance profiler to see if there are places we can improve it
DARMA-tasking/LB-analysis-framework pull request #460
Opened 2023-10-10 20:09 UTC by cwschilly

Fixes #441

2023-10-10 20:18 UTC, cwschilly commented
While some of the "optimizations" seem trivial, others are good catches. For instance, the profiler caught this duplicated code in the `run()` function of `LBAF_app.py`:

```python
for phase_id in self.__parameters.phase_ids:
    # Create a phase and populate it
    phase = Phase(
        self.__logger, phase_id, reader=reader)
    phase.populate_from_log(phase_id)
    phases[phase_id] = phase
    phase = Phase(
        self.__logger, phase_id, reader=reader)
    phase.populate_from_log(phase_id)
    phases[phase_id] = phase
```
---
I timed the execution of the run function through multiple iterations of adding these optimizations. Averaging the times from three runs on `challenging-toy-hundreds-tasks.yaml`, here are the results:

| Change | Average `run()` time (s) |
| ----------- | ----------- |
| Original state      | 66.327 |
| Change `print_statistics` call   | 52.208 |
| Change `arrangement` sorting | 59.030 |
| Remove duplicated phase block | 38.445 |
| Rework `qoi_request` list | 45.639 |

---

Clearly some changes were more impactful than others. The timings also varied a lot, so it's not worth going by these alone. Let me know @ppebay @lifflander if you want to keep any of these changes. I'll update this table if I make any more revisions.

2023-10-11 22:57 UTC, ppebay requested changes
Some good findings and fixes!

A couple of minor details to be changes, and we should be good to go

2023-10-11 22:57 UTC, ppebay commented on src/lbaf/Applications/LBAF_app.py
> -                phase = Phase(
That duplicate block is also deleted in PR #451 -- this may cause a conflict or not, we shall see

2023-10-11 22:57 UTC, ppebay commented on src/lbaf/Execution/lbsInformAndTransferAlgorithm.py
line 73, `r` should be replace with `rank`

2023-10-12 14:02 UTC, cwschilly commented on src/lbaf/Execution/lbsInformAndTransferAlgorithm.py
Resolved, thanks

2023-10-12 14:03 UTC, cwschilly commented
Thanks @ppebay , I made the requested change.

2023-10-13 15:41 UTC, ppebay approved these changes
Good findings

2023-10-13 17:40 UTC, merged