#542: Fix as many pylint issues as possible before release
DARMA-tasking/LB-analysis-framework pull request #546
Opened 2024-09-24 20:27 UTC by cwschilly

Fixes #542 

These are all "easy" fixes; warnings that would require more refactoring of the code (e.g. `too-many-*`) have not been resolved.]

2024-09-27 12:08 UTC, tlamonthezie requested changes
Seems to be good.

However some pylint warnings could be still removed for `lbsTemperedCriterion`, `lbsPrescribedPermutationAlgorithm`, `lbsVisualizer`

Here is my output with only errors or warnings verifications:
```shell
$ pylint --rcfile=.pylintrc --disable=R,C src
************* Module lbaf.Execution.lbsTemperedCriterion
src/lbaf/Execution/lbsTemperedCriterion.py:8:0: W0223: Method 'estimate' is abstract in class 'CriterionBase' but is not overridden in child class 'TemperedCriterion' (abstract-method)
************* Module lbaf.Execution.lbsPrescribedPermutationAlgorithm
src/lbaf/Execution/lbsPrescribedPermutationAlgorithm.py:80:12: W1309: Using an f-string that does not have any interpolated variables (f-string-without-interpolation)
src/lbaf/Execution/lbsPrescribedPermutationAlgorithm.py:77:8: W0612: Unused variable 'stats' (unused-variable)
src/lbaf/Execution/lbsPrescribedPermutationAlgorithm.py:1:0: W0611: Unused import random (unused-import)
src/lbaf/Execution/lbsPrescribedPermutationAlgorithm.py:2:0: W0611: Unused import time (unused-import)
src/lbaf/Execution/lbsPrescribedPermutationAlgorithm.py:6:0: W0611: Unused Rank imported from Model.lbsRank (unused-import)
src/lbaf/Execution/lbsPrescribedPermutationAlgorithm.py:7:0: W0611: Unused Message imported from Model.lbsMessage (unused-import)
************* Module lbaf.IO.lbsVisualizer
src/lbaf/IO/lbsVisualizer.py:53:8: W0101: Unreachable code (unreachable)
```

Note: the last one will be removed by PR #543

2024-09-27 16:39 UTC, cwschilly commented
Thanks @tlamonthezie , I fixed the warnings in `lbsPrescribedPermutationAlgorithm.py`.

I left the `lbsVisualizer` as it is because (like you said) it'll be removed very soon. 

As for the `estimate` warning, it looks like `CriterionBase` defines this as a method, but it's not clear to me whether it's really used.

`TemperedLB` doesn't implement it at all (which causes the warning), while `StrictLocalizingCriterion` implements it by simply forwarding it to the compute function:

```python
def estimate(self, r_src: Rank, o_src: list, *args) -> float:
        """Estimate is compute because all information is local for this criterion."""
        return self.compute(r_src, o_src, *args)
```

It seems then that we could just remove the `estimate` function entirely. I mentioned this to @ppebay -- I think this will require further investigation outside of this PR.

2024-09-27 21:39 UTC, ppebay commented
> Thanks @tlamonthezie , I fixed the warnings in `lbsPrescribedPermutationAlgorithm.py`.
> 
> I left the `lbsVisualizer` as it is because (like you said) it'll be removed very soon.
> 
> As for the `estimate` warning, it looks like `CriterionBase` defines this as a method, but it's not clear to me whether it's really used.
> 
> * `TemperedCriterion` doesn't implement it at all (which causes the warning)
> * `StrictLocalizingCriterion` implements it by simply forwarding it to the compute function:
> 
> ```python
> def estimate(self, r_src: Rank, o_src: list, *args) -> float:
>         """Estimate is compute because all information is local for this criterion."""
>         return self.compute(r_src, o_src, *args)
> ```
> 
> It seems then that we could just remove the `estimate` function entirely. I mentioned this to @ppebay -- I think this will require further investigation outside of this PR.

Yes, please create follow-on issue @cwschilly and let's leave it in the code for now. Thanks

2024-09-27 21:39 UTC, ppebay approved these changes

2024-09-30 11:52 UTC, tlamonthezie approved these changes

2024-09-30 14:14 UTC, merged